Kotlin. Homework #2
Ythosa/shallow-size-kotlin-plugin pull request #1
Opened 2022-03-18 16:21 UTC by Ythosa

2022-03-23 20:25 UTC, illided requested changes

2022-03-23 20:25 UTC, illided commented on shallowSizePlugin/src/main/kotlin/spbu/kotlin/shallow/plugin/AddShallowSizeMethod.kt
> +                if (clazz.isData) clazz.functions.find { it.name.asString() == ShallowSizeSignature.name }!!
Надо еще проверить, что количество параметров 0

2022-03-23 20:25 UTC, illided commented on shallowSizePlugin/src/main/kotlin/spbu/kotlin/shallow/plugin/AddShallowSizeMethod.kt
> +                if (clazz.isData) clazz.functions.find { it.name.asString() == ShallowSizeSignature.name }!!
И давай попробуем обойтись без `!!`

2022-03-23 20:37 UTC, Ythosa commented on shallowSizePlugin/src/main/kotlin/spbu/kotlin/shallow/plugin/AddShallowSizeMethod.kt
> +                if (clazz.isData) clazz.functions.find { it.name.asString() == ShallowSizeSignature.name }!!
Что вы называете параметрами?

2022-03-24 18:07 UTC, Belgrak commented on shallowSizePlugin/src/main/kotlin/spbu/kotlin/shallow/plugin/AddShallowSizeMethod.kt
> +                if (clazz.isData) clazz.functions.find { it.name.asString() == ShallowSizeSignature.name }!!
> Надо еще проверить, что количество параметров 0

@illided 
Методом проб и ошибок я выяснил, что там вроде один параметр обязателен (по крайней мере при использовании .allParametersCount. Возможно параметром является какая-нибудь характеристика функции). При проверке на полное отсутствие параметров тесты падают.

2022-03-24 18:50 UTC, illided commented on shallowSizePlugin/src/main/kotlin/spbu/kotlin/shallow/plugin/AddShallowSizeMethod.kt
> +                if (clazz.isData) clazz.functions.find { it.name.asString() == ShallowSizeSignature.name }!!
Можно прописать `valueParameters.isEmpty()`. Насколько я понимаю это считает настоящие параметры, без всяких котлиновских скрытых трюков

2022-03-27 14:17 UTC, illided approved these changes
Все ок. Кидаю тебя на Настю

2022-03-28 08:06 UTC, nbirillo requested changes

2022-03-28 08:06 UTC, nbirillo commented on .github/workflows/main.yaml
> +      - name: Run build
А давай ты добавишь еще возможность скачивания артефактов в случае, если CI не проходит (тест репорты например)? можно почитать [тут](https://github.com/actions/upload-artifact)

2022-03-28 08:06 UTC, nbirillo commented on .github/workflows/main.yaml
> +        run: ./gradlew detekt
Было бы классно не прости включить дефолтный конфиг, а научиться добавлять еще свой в репозиторий) добавь настройку каких-нибудь парочки правил, чтобы показать, что ты понимаешь как это делается

2022-03-28 08:06 UTC, nbirillo commented on shallowSizePlugin/src/main/kotlin/spbu/kotlin/shallow/plugin/AddShallowSizeMethod.kt
> +}
Раз уж добавился этот класс для описания функции, то и константы выше можно тоже сделать не top-level в таком случае и все объединить + вынести тогда в утилиты куда-нибудь в соседний файлик

2022-03-28 08:06 UTC, nbirillo commented on shallowSizePlugin/src/main/kotlin/spbu/kotlin/shallow/plugin/AddShallowSizeMethod.kt
> +                    newDeclaration = ShallowSizeSignature.let { signature ->
А зачем тебе let и тд? кажется проще все вынести в companion и использовать без `ShallowSizeSignature.let`. ну и в целом вообще сразу можно использовать без `ShallowSizeSignature.let`

2022-03-28 08:06 UTC, nbirillo commented on shallowSizePlugin/src/main/kotlin/spbu/kotlin/shallow/plugin/AddShallowSizeMethod.kt
> +                            fun ${signature.name}(${signature.parameters}): ${signature.returnType} = TODO()
Плохо оставлять чистые TODO даже просто в качестве заглушки. Напиши там внутри сообщение какое-нибудь. Если у тебя сломается IR генерация и тело не заменится, то хотя бы ошибка будет понятная

2022-03-28 08:06 UTC, nbirillo commented on shallowSizePlugin/src/main/kotlin/spbu/kotlin/shallow/plugin/AddShallowSizeMethod.kt
> +                        it.name.asString() == ShallowSizeSignature.name && it.valueParameters.isEmpty()
Можно сделать функцию-расширение для IrFunction, которая будет называться что-то isShallowSizeFunction и вынести туда эти условия, это увеличит читаемость и понятность кода

2022-03-28 08:06 UTC, nbirillo commented on shallowSizePluginTest/src/main/kotlin/spbu/kotlin/shallow/plugin/ShallowSizeTest.kt
> +        val shallowSizeMethod = testingClass::class.memberFunctions.find { it.name == "shallowSize" }!!
Избавляйся от !! и кидай нормальную ошибку)

2022-04-01 04:52 UTC, Ythosa commented on .github/workflows/main.yaml
> +        run: ./gradlew detekt
Ну вот, я не дурак, правда, я умею :(( : https://github.com/Ythosa/linkschecker/blob/main/.github/workflows/go.yml

2022-04-01 04:53 UTC, Ythosa commented on shallowSizePlugin/src/main/kotlin/spbu/kotlin/shallow/plugin/AddShallowSizeMethod.kt
> +                    newDeclaration = ShallowSizeSignature.let { signature ->
`ShallowSizeSignature.xxx` используется слишком часто, много буковок получается

2022-04-01 15:10 UTC, Ythosa commented on shallowSizePlugin/src/main/kotlin/spbu/kotlin/shallow/plugin/AddShallowSizeMethod.kt
> +}
А почему вы назваете object declaration классом?

2022-04-04 07:40 UTC, nbirillo approved these changes
Теперь все хорошо, можно засчитывать)

2022-04-04 07:40 UTC, merged